### PR TITLE
Fix .isUnread class exclusion for .divider

### PR DESCRIPTION
**Pull request by nike4613**
The `:not([class="class"])` syntax checks for only the class in the quotes, not that it has that class. This fixes that.

### CODE REVIEW

**Comment by FlashAL** [comment]
please remind me what this class is and to which element it is attached in the discord

**Comment by nike4613** [comment]
That is the unread indicator line. It ends up being dark otherwise.

**Comment by FlashAL** [comment]
screenshot please cus i dont understand where is this unread thing with class name starts by "divider"

**Comment by nike4613** [comment]
image

**Comment by FlashAL** [comment]
oh the problem that it might have this ```.divider-JfaTT5:not([class="isUnread-3Ef-o9"])``` not this ```.divider-JfaTT5:not(.isUnread-3Ef-o9)``` is because of BD and Discord updates sometimes being buggy and it broke DM visability

**Comment by FlashAL** [comment]
Screenshot_2
Screenshot_3
+ when you use ```.divider-JfaTT5:not(.isUnread-3Ef-o9)``` it dosnt make sence because its not working

**Comment by nike4613** [comment]
The bottom one is what I expect, and is what this PR achieves.

**Comment by FlashAL** [comment]
your PR just unpin border top color change from this class this is the same as deleting the entire line in the code so your change dosnt make sence

**Comment by nike4613** [comment]
What the `:not([class=...])` selector does is it excludes nodes with the `class` attribute *exactly matching* the string that is given. If the node has any classes besides the one provided, it won't exclude it. Because it is on a class selector that is not exactly what is provided, that means that *this rule will never not apply*. There are no elements with `.divider-...` for which the rule will not match. This is a problem precisely because the unread indicator is supposed to have a red line across to make it ovbious where the divider is marking.

**Comment by FlashAL** [comment]
the original look of this indecator in my theme is dark not red you can modify the theme for self use how ever you want.
iam closing this reques if you dont have other problems to speak about

**Comment by nike4613** [comment]
The CSS in question is *clearly intended* to do what this PR makes it actually do, just not correctly. If that isn't what you actually wanted it to do, that's one thing, but fundamentally the `:not` selector doesn't serve any purpose currently. One way or another, it should be cleaned up.

**Comment by FlashAL** [comment]
> The CSS in question is _clearly intended_ to do what this PR makes it actually do, just not correctly. If that isn't what you actually wanted it to do, that's one thing, but fundamentally the `:not` selector doesn't serve any purpose currently. One way or another, it should be cleaned up.

yeah i understant that its just an old line in the code that i forget about ill delete it in next commit iam sure that the code has much things that dosnt make sence i have to fix but "if it work never touch it" :)

**Pull request closed without merging**
